<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVc9Ggqp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVc9Ggqp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVc9Ggqp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVc9Ggqp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVc9Ggqp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Vc9Ggqp',
    'container.build_id' => '319947c1',
    'container.build_time' => 1576146564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVc9Ggqp');
